### ISSUE TITLE
Request:  Animated Fire Logo

### ISSUE THREAD

**Issue by SaintPeter** [FreeCodeCamp/FCCAssets#2]
I was going to do some videos and I was thinking that having a 2d animated version of the FCC campfire icon would be awesome. I'm thinking a 2-3 seconds of looping "flames" of the fire.  It could be used as part of a title card for FCC related videos.

This image:
<img src="https://raw.githubusercontent.com/FreeCodeCamp/FCCAssets/master/Logos%20and%20Covers/fcc-app-icon.png" width="200px" height="200px" />

Both the inner and outer flame could be animated.

**Comment by Rybar** [comment]
That sounds like a fun project, I've done a bit of motion graphics work,
I'll see what I can do.

**Comment by SaintPeter** [comment]
Just thinking some more about it, I could see it going two ways:
1) Looping animated flickering fire, as describe above.  Maybe "rotoscoped" from real flames.
2) A single pass animation that maybe started with a "real" fire and then flickered into the logo.  Something long the lines of a movie studio title card.

Either way would be pretty cool.  Just something to give a little motion/action to the lead in.

**Comment by iheartkode** [comment]
That would be pretty neat, @Rybar  let me know what you come up with.

**Comment by iheartkode** [comment]
I'm going to attempt this

**Comment by iheartkode** [comment]
I can't make the animation and rybar seems busy, maybe ask someone in fcc chat? Closing this.
